### ISSUE TITLE
Script does not work in online mode.

### ISSUE THREAD

**Issue by Akeyroid7** [Akeyroid7/a7-impulse#2]
Script stops with error in online mode.

[![Twitter](https://pbs.twimg.com/media/F_UGczuaEAAH_20?format=png&name=small)](https://twitter.com/Akeyroid7/status/1726293484628496632)

It appears that `physics.startPhysicsWorker` is not available in online mode.

## Task

- [ ] Rewrite scripts so that errors do not occur when starting in online mode.

## Note

I would consider other solutions available in online mode.

**Comment by Akeyroid7** [comment]
The easiest way to run A7-Impulse in online mode is to embed the script in Gamepad FX.
Gamepad FX called [AC-X](https://www.racedepartment.com/downloads/ac-x-gamepadfx.62308/) has the ability to load additional scripts as "Extra".
I would like to be able to add A7-Impulse to this.

## Task

- [ ] Create a version that is an "Extra" module that works with AC-X.
- [ ] Describe in README.md how to use the modules with other Gamepad FX. (e.g. A7-Assist, Advanced Gamepad Assist, etc.)

**Comment by Seyrlaun** [comment]
Hey, I figured out why this crashes online. It looks like the game blocks physics.startPhysicsWorker on multiplayer.

I managed to fix it by moving the logic out of the worker and directly into the main script.update loop. It works perfectly online now since it runs on the main thread.

This is the updated A7-Impluse.lua

`if ac.getPatchVersionCode() < 2651 then return end

local __gamepadIndex = ac.INIConfig.controlsConfig():get('X360', 'JOYPAD_INDEX', 0)
local TRIGGER_RUMBLE_INTENSITY = 0.1
local TRIGGER_RUMBLE_MIN = 0.1
local TRIGGER_RUMBLE_MAX_SLIP = 1000
local TRIGGER_RUMBLE_ABS = 0.5
local PRIORITY = -1

local function weightedAverage(values, weights)
  if #values < 1 then error('There is no value.') end
  if #values ~= #weights then error('Number of elements does not match.') end
  local weightedValue = 0
  local totalWeight = 0
  for i, v in ipairs(values) do
    weightedValue = weightedValue + v * weights[i]
    totalWeight = totalWeight + weights[i]
  end
  if totalWeight == 0 then return 0 end
  return weightedValue / totalWeight
end

local function ellipseRadius(w, h, rad)
  return w * h / math.sqrt(w ^ 2 * math.sin(rad) ^ 2 + h ^ 2 * math.cos(rad) ^ 2)
end

function script.update(dt)
  local car = ac.getCar(0)
  if not car then return end

  local wData = {}
  for i = 0, 3 do
    wData[i] = {}
    if car.wheels[i] then
        wData[i].fAngleRad = math.atan2(car.wheels[i].fy, car.wheels[i].fx)
    else
        wData[i].fAngleRad = 0
    end
  end

  local ndSlipB = (function(values, weights)
    for i = 0, 1 do
      if car.wheels[i] then
        values[i] = car.wheels[i].ndSlip * math.cos(wData[i].fAngleRad) * ellipseRadius(car.wheels[i].dx, car.wheels[i].dy, wData[i].fAngleRad) / car.wheels[i].dx
        weights[i] = car.wheels[i].load
      end
    end
    return weightedAverage(values, weights) * math.sign(car.gear)
  end)({}, {})

  local ndSlipA = (function(values, weights)
    for i = 0, 3 do
      if car.wheels[i] then
        values[i] = car.wheels[i].ndSlip * -math.cos(wData[i].fAngleRad) * ellipseRadius(car.wheels[i].dx, car.wheels[i].dy, wData[i].fAngleRad) / car.wheels[i].dx
        weights[i] = car.wheels[i].load
      end
    end
    return weightedAverage(values, weights) * math.sign(car.gear)
  end)({}, {})

  local impulseL = math.min(1 < ndSlipB and (math.log(ndSlipB, TRIGGER_RUMBLE_MAX_SLIP) * (1 - TRIGGER_RUMBLE_MIN) + TRIGGER_RUMBLE_MIN) or 0 + (car.absInAction and TRIGGER_RUMBLE_ABS or 0), 1)
  local impulseR = math.min(1 < ndSlipA and (math.log(ndSlipA, TRIGGER_RUMBLE_MAX_SLIP) * (1 - TRIGGER_RUMBLE_MIN) + TRIGGER_RUMBLE_MIN) or 0, 1)

  local xbox = ac.setXbox(__gamepadIndex, PRIORITY)
  if xbox then
    xbox.triggerLeft = math.saturate(impulseL * TRIGGER_RUMBLE_INTENSITY)
    xbox.triggerRight = math.saturate(impulseR * TRIGGER_RUMBLE_INTENSITY)
  end
end`
